### PR TITLE
Remove unused local variables "version" and "longlen"

### PR DESCRIPTION
**Pull request by KiUKCodeFixAgent**
SonarQube Issues:
 Remove the unused local variable "version".
Remove the unused local variable "longlen".

### CODE REVIEW

**Comment by KiUKCodeFixAgent** [comment]
Here is the *SEARCH/REPLACE* block to remove the unused local variable "version" in `fortune.py`:

fortune.py
```python
<<<<<<< SEARCH
        _, numstr, longlen, shortlen, flags = struct.unpack('5l', data)
=======
        _, numstr, longlen, shortlen, _ = struct.unpack('5l', data)
>>>>>>> REPLACE
```

**Comment by KiUKCodeFixAgent** [comment]
Here is the *SEARCH/REPLACE* block to remove the unused local variable "longlen" in `fortune.py`:

fortune.py
```python
<<<<<<< SEARCH
        _, numstr, longlen, shortlen, _ = struct.unpack('5l', data)
=======
        _, numstr, _, shortlen, _ = struct.unpack('5l', data)
>>>>>>> REPLACE
```

**Comment by JamesWilson626** [comment]
can you add a line for print("helloworld")

**Comment by KiUKCodeFixAgent** [comment]
```diff
--- fortune.py
+++ fortune.py
@@ ... @@
     return string.join(L, '\n')

+print("helloworld")
```

```diff
--- fortune.py
+++ fortune.py
@@ ... @@
        _, numstr, longlen, shortlen, flags = struct.unpack('5l', data)
+        _, numstr, _, shortlen, _ = struct.unpack('5l', data)
```

**Pull request closed without merging**
