### PR TITLE
Replace print statements by built-in functions

### PR DESCRIPTION
**Pull request by KiUKCodeFixAgent**
SonarQube Issues:
 Replace print statement by built-in function.
Replace print statement by built-in function.
Replace print statement by built-in function.
Replace print statement by built-in function.
Replace print statement by built-in function.

### CODE REVIEW

**Comment by KiUKCodeFixAgent** [comment]
Here is the required change to replace the `print` statement with the built-in `print` function:

letters.py
```python
<<<<<<< SEARCH
            print '\nOK; give up if you like.'
=======
            print('\nOK; give up if you like.')
>>>>>>> REPLACE
```

**Comment by KiUKCodeFixAgent** [comment]
Here is the change to replace the print statement with the built-in function:

letters.py
```python
<<<<<<< SEARCH
                print "You don't have enough information yet."
=======
                print("You don't have enough information yet.")
>>>>>>> REPLACE
```

**Comment by KiUKCodeFixAgent** [comment]
Here is the change to replace the print statement with the built-in function:

letters.py
```python
<<<<<<< SEARCH
print "How do you know it isn't", temp[r]+',',
print "for example?"
=======
print("How do you know it isn't", temp[r]+',', end=' ')
print("for example?")
>>>>>>> REPLACE
```

**Comment by KiUKCodeFixAgent** [comment]
Here is the required change to replace the print statement with the built-in function:

strfile.py
```python
<<<<<<< SEARCH
    print "Usage: strfile.py <filename>"
=======
    print("Usage: strfile.py <filename>")
>>>>>>> REPLACE
```

**Comment by KiUKCodeFixAgent** [comment]
To resolve the SonarQube issue by replacing the print statement with a built-in function, we will use the `print()` function. Here is the *SEARCH/REPLACE* block:

strfile.py
```python
<<<<<<< SEARCH
print('''"%s.dat" created
There were %i strings
Longest string: %i bytes
Shortest string: %i bytes''' % (filename, numstr, longest, shortest))
=======
print(f'"{filename}.dat" created\n'
      f'There were {numstr} strings\n'
      f'Longest string: {longest} bytes\n'
      f'Shortest string: {shortest} bytes')
>>>>>>> REPLACE
```

**Comment by sonanuga-reply** [comment]
Ensure that in letters.py print statements are all changed to Python3's style

**Comment by KiUKCodeFixAgent** [comment]
Here are the changes to update all `print` statements in `letters.py` to Python 3 style:

```diff
--- letters.py
+++ letters.py
@@ ... @@
-            print '\nOK; give up if you like.'
+            print('\nOK; give up if you like.')
@@ ... @@
-                print "You don't have enough information yet."
+                print("You don't have enough information yet.")
@@ ... @@
-                print "How do you know it isn't", temp[r]+',',
-                print "for example?"
+                print("How do you know it isn't", temp[r]+',', end=' ')
+                print("for example?")
@@ ... @@
-print """This is a guessing game about capital letters.
-You can ask various questions about the features of the letter:
-curves, loose ends, obliques (or diagonals), horizontals, verticals.
-To make a guess, just enter the letter of your choice.
-
-Sample transcript:
-        Next? curves?
-        1.
-        Good question.
-        Next? c
-        You don't have enough information yet.
-        How do you know it isn't s, for example?
-        Next? horizontals?
-        0.
-        Next? s
-        You don't have enough information yet.
-        How do you know it isn't c, for example?
-"""
+print("""This is a guessing game about capital letters.
+You can ask various questions about the features of the letter:
+curves, loose ends, obliques (or diagonals), horizontals, verticals.
+To make a guess, just enter the letter of your choice.
+
+Sample transcript:
+        Next? curves?
+        1.
+        Good question.
+        Next? c
+        You don't have enough information yet.
+        How do you know it isn't s, for example?
+        Next? horizontals?
+        0.
+        Next? s
+        You don't have enough information yet.
+        How do you know it isn't c, for example?
+""")
@@ ... @@
-raw_input("Press Return>")
+input("Press Return>")
```

These changes convert all the old Python 2 `print` statements to the Python 3 `print()` function, and also update `raw_input()` to `input()`, which is the Python 3 equivalent.

**Comment by kanishk-reply** [comment]
add a hello world print statement at the start of the letters file

**Comment by KiUKCodeFixAgent** [comment]
Here are the changes to the `letters.py` file to add a "Hello World" print statement at the start and to replace all old Python 2 `print` statements with Python 3 `print()` function calls:

```diff
--- letters.py
+++ letters.py
@@ ...
+print("Hello World")
@@ ...
-print '\nOK; give up if you like.'
+print('\nOK; give up if you like.')
@@ ...
-print "You don't have enough information yet."
+print("You don't have enough information yet.")
@@ ...
-print "How do you know it isn't", temp[r]+',',
-print "for example?"
+print("How do you know it isn't", temp[r]+',', end=' ')
+print("for example?")
@@ ...
-print """This is a guessing game about capital letters.
-You can ask various questions about the features of the letter:
-curves, loose ends, obliques (or diagonals), horizontals, verticals.
-To make a guess, just enter the letter of your choice.
-
-Sample transcript:
-        Next? curves?
-        1.
-        Good question.
-        Next? c
-        You don't have enough information yet.
-        How do you know it isn't s, for example?
-        Next? horizontals?
-        0.
-        Next? s
-        You don't have enough information yet.
-        How do you know it isn't c, for example?
-"""
+print("""This is a guessing game about capital letters.
+You can ask various questions about the features of the letter:
+curves, loose ends, obliques (or diagonals), horizontals, verticals.
+To make a guess, just enter the letter of your choice.
+
+Sample transcript:
+        Next? curves?
+        1.
+        Good question.
+        Next? c
+        You don't have enough information yet.
+        How do you know it isn't s, for example?
+        Next? horizontals?
+        0.
+        Next? s
+        You don't have enough information yet.
+        How do you know it isn't c, for example?
+""")
@@ ...
-raw_input("Press Return>")
+input("Press Return>")
```

These changes ensure that the code is updated to Python 3 standards and includes the requested "Hello World" print statement at the start of the file.

**Comment by KiUKCodeFixAgent** [comment]
Here are the changes to the `letters.py` file to add a "Hello World" print statement at the start and to replace all old Python 2 `print` statements with Python 3 `print()` function calls:

```diff
--- letters.py
+++ letters.py
@@ ...
+print("Hello World")
@@ ...
-print '\nOK; give up if you like.'
+print('\nOK; give up if you like.')
@@ ...
-print "You don't have enough information yet."
+print("You don't have enough information yet.")
@@ ...
-print "How do you know it isn't", temp[r]+',',
-print "for example?"
+print("How do you know it isn't", temp[r]+',', end=' ')
+print("for example?")
@@ ...
-print """This is a guessing game about capital letters.
-You can ask various questions about the features of the letter:
-curves, loose ends, obliques (or diagonals), horizontals, verticals.
-To make a guess, just enter the letter of your choice.
-
-Sample transcript:
-        Next? curves?
-        1.
-        Good question.
-        Next? c
-        You don't have enough information yet.
-        How do you know it isn't s, for example?
-        Next? horizontals?
-        0.
-        Next? s
-        You don't have enough information yet.
-        How do you know it isn't c, for example?
-"""
+print("""This is a guessing game about capital letters.
+You can ask various questions about the features of the letter:
+curves, loose ends, obliques (or diagonals), horizontals, verticals.
+To make a guess, just enter the letter of your choice.
+
+Sample transcript:
+        Next? curves?
+        1.
+        Good question.
+        Next? c
+        You don't have enough information yet.
+        How do you know it isn't s, for example?
+        Next? horizontals?
+        0.
+        Next? s
+        You don't have enough information yet.
+        How do you know it isn't c, for example?
+""")
@@ ...
-raw_input("Press Return>")
+input("Press Return>")
```

These changes ensure that the code is updated to Python 3 standards and includes the requested "Hello World" print statement at the start of the file.

**Pull request closed without merging**
