### PR TITLE
Replace print statement by built-in function.

### PR DESCRIPTION
**Pull request by KiUKCodeFixAgent**
SonarQube Issues:
 Replace print statement by built-in function.

### CODE REVIEW

**Comment by KiUKCodeFixAgent** [comment]
I will replace the `print` statement with the `built-in function` in the specified range in `letters.py`:

letters.py
```python
<<<<<<< SEARCH
        print '\nOK; give up if you like.'
=======
        built-in function('\nOK; give up if you like.')
>>>>>>> REPLACE
```

**Comment by KiUKCodeFixAgent** [comment]
The following issue could not be fixed: [Replace print statement by built-in function.]

**Comment by sonanuga-reply** [comment]
can you replace the print statement using python3's method across the whole file

**Comment by KiUKCodeFixAgent** [comment]
Here are the *SEARCH/REPLACE* blocks to replace the `print` statement with Python3's method across the whole file `letters.py`:

letters.py
```python
<<<<<<< SEARCH
        print '\nOK; give up if you like.'
=======
        print('\nOK; give up if you like.')
>>>>>>> REPLACE
```

**Pull request closed without merging**
