### PR TITLE
Remove unused local variables "version" and "longlen".

### PR DESCRIPTION
**Pull request by KiUKCodeFixAgent**
SonarQube Issues:
 Remove the unused local variable "version".
Remove the unused local variable "longlen".

### CODE REVIEW

**Comment by KiUKCodeFixAgent** [comment]
Here is the *SEARCH/REPLACE* block to remove the unused local variable "version" from line 55 in `fortune.py`:

fortune.py
```python
<<<<<<< SEARCH
        _, numstr, longlen, shortlen, flags = struct.unpack('5l', data)
=======
        _, numstr, longlen, shortlen, _ = struct.unpack('5l', data)
>>>>>>> REPLACE
```

**Comment by KiUKCodeFixAgent** [comment]
Here is the *SEARCH/REPLACE* block to remove the unused local variable "longlen" from line 57 in `fortune.py`:

fortune.py
```python
<<<<<<< SEARCH
        _, numstr, longlen, shortlen, _ = struct.unpack('5l', data)
=======
        _, numstr, _, shortlen, _ = struct.unpack('5l', data)
>>>>>>> REPLACE
```

**Comment by kanishk-reply** [comment]
add a hello world print statement at the start of the file

**Comment by KiUKCodeFixAgent** [comment]
```diff
--- fortune.py
+++ fortune.py
@@ ... @@
+print("Hello, World!")
+
@@ ... @@
-        _, numstr, longlen, shortlen, flags = struct.unpack('5l', data)
+        _, numstr, _, shortlen, flags = struct.unpack('5l', data)
```

**Pull request closed without merging**
